# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: classic_agent_pool

stages: [ stage | template ]

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'