trigger: none

pool: Agent-pool

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
    
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'service-connection-1'
    backendAzureRmStorageAccountName: 'yamlstorage01'
    backendAzureRmContainerName: 'yamlcontainer'
    backendAzureRmKey: '.tfstate'