name: manual workflow

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  manual_validation:
    runs-on: ubuntu-latest
    needs: build

    steps:
     - name: Manual Workflow Approval
       uses: trstringer/manual-approval@v1.9.0
       with:
         approvers: goyalece@gmail.com
         secret: ${{ secrets.APPROVAL_SECRET }}
         minimum-approvals: 1

  deploy:
    runs-on: runner
    needs: manual_validation

    steps:
     - name: Terraform Apply
       run: terraform apply -auto-approve
