name: "my first workflow"

on:
  push:
    branches:
      - 'features/**'
      - 'main'
      - 'hotfix/**'

jobs:
  terraform:
    name: terraform init to plan
    runs-on: runner
    steps: 
      - name: terraform init
        run: echo terraform init
  
